package test;



/**订单详情0041*/
public class CacheRespondParam0041{
/** 订单号 备注:*/
public String orderNo;
/** 业务代号 备注:*/
public String busiNo;
/** 渠道代号 备注:*/
public String channelNo;
/** 支付方式 备注:*/
public String payType;
/** 下单日期 备注:*/
public String bookDate;
/** 处理机构 备注:*/
public String dealBrch;
/** 支付状态 备注:*/
public String payStatus;
/** 处理状态 备注:*/
public String dealStatus;
/** 配送方式 备注:自提方式：自提网点代号 、自提码生效；寄递方式：收件人信息 生效*/
public String shipType;
/** 自提网点代号 备注:*/
public String brchNo;
/** 自提码 备注:*/
public String toTheCode;
/** 收货人姓名 备注:收件人信息*/
public String recvName;
/** 详细地址 备注:*/
public String detailAddress;
/** 收件手机号码 备注:*/
public String mobileNo;
/** 邮编 备注:*/
public String postCode;
/** 订单总金额 备注:*/
public float orderAmt;
/** 商品总金额 备注:*/
public float merchAmt;
/** 配送费用 备注:*/
public float shipFee;
/** 已付金额 备注:*/
public float hasPayMoney;
/** 订单备注信息 备注:*/
public String orderRemark;
/** 发票开具类型 备注:不开、个人、单位*/
public String invoiceType;
/** 发票抬头 备注:当发票类型为“单位”时生效*/
public String invoiceTitle;
/** 预处理单号 备注:个性化定制业务才有预处理单号*/
public String prepNumber;
/** 操作类型 备注:支付、取消、换货等*/
public String operationType;
/** 操作截止日期 备注:*/
public String operationEndDate;
/** 处理时间 备注:yymmddhhmmss*/
public String dealTime;
/** 处理类型 备注:*/
public String dealType;
/** 处理内容 备注:*/
public String dealContent;
/** 处理人 备注:*/
public String dealPerson;
/** 事件类型 备注:退款、补款、摇号、换货*/
public String eventType;
/** 事件状态 备注:未审核、审核通过、审核不通过等*/
public String eventStatus;
/** 事件描述 备注:*/
public String eventDesc;
/** 支付流水 备注:*/
public String paySeq;
/** 支付流水状态 备注:支付、退款、补款*/
public String paySeqStatus;
/** 金额 备注:*/
public float payMoney;
/** 流水操作状态 备注:*/
public String payOperStatus;
/** 操作时间 备注:*/
public String payDealTime;
/** 银行流水 备注:*/
public String bankSeq;
/** 备注 备注:*/
public String payRemark;
/** 子订单数量 备注:循环域开始*/
public int subOrderNum;
/** 子订单号 备注:*/
public String subOrderNo1;
/** 子订单状态 备注:*/
public String subOrderStatus;
/** 子订单总金额 备注:*/
public float subOrderAmt;
/** 商品总金额 备注:*/
public float subMerchAmt;
/** 配送费用 备注:*/
public float subShipFee;
/** 子订单数量 备注:循环域结束*/
//public int subOrderNum;
/** 子订单号 备注:*/
public String subOrderNo2;
/** 处理时间 备注:yymmddhhmmss*/
public String subdealTime;
/** 处理类型 备注:*/
public String subdealType;
/** 处理内容 备注:*/
public String subdealContent;
/** 处理人 备注:*/
public String subdealPerson;
/** 子订单号 备注:*/
public String subOrderNo3;
/** 物流公司 备注:*/
public String logistCompany;
/** 物流单号 备注:yymmddhhmmss*/
public String logistNum;
/** 处理时间 备注:yymmddhhmmss*/
public String logistDealTime;
/** 商品代号 备注:*/
public String merchID;
/** 图片ID 备注:*/
public String merchPicID;
/** 商品名称 备注:*/
public String merchName;
/** 商品规格 备注:*/
public String normsType;
/** 模式单价 备注:*/
public float normsPrice;
/** 商品购买数量 备注:*/
public int merchNum;
}


